### ISSUE TITLE
Apple Custom B2B

### ISSUE THREAD

**Issue by faogustavo** [kimxogus/react-native-version-check#13]
Does it works with custom b2b too?

**Comment by kimxogus** [comment]
Sorry for late response.
I have no idea even what custom b2b is. I have no experience in publishing iOS app honestly.

**Comment by tschoffelen** [comment]
This library currently doesn't work with custom B2B apps, since there is no public information source about the latest version of those apps available, rendering the method we use to get the update info (doing a HTTP call to iTunes) moot.

If you want to support a similar system for an app that isn't publicly available, you will probably have to build your own back-end API to supply this info.

In such cases there isn't a one-size-fits-all solution, so I don't think this falls within the scope of this library.
