### ISSUE TITLE
Allow check build numbers (beta updates)

### ISSUE THREAD

**Issue by ararog** [kimxogus/react-native-version-check#3]
It would be nice to allow the module to work with beta versions sent over testflight, is it possible?

**Comment by kimxogus** [comment]
I've never used testflight. It will be possible if someone who know it contributes.

**Comment by rf1804** [comment]
@ararog It is not possible for TestFlight, as beta updates are only available to specific defined set of people because of which app information is not publicly available. Whole workflow of version-check depends on fetching app information and comparing with current running app version and latest available app version on specific store.
