### ISSUE TITLE
Can't get getStoreUrl() working

### ISSUE THREAD

**Issue by ziyafenn** [kimxogus/react-native-version-check#57]
Hello. I'm trying to use `VersionCheck.getStoreUrl()` to get the url and link it to button, but i'm getting following error on console:

```
Error: At least one of appID and appName is empty.
Error: At least one of appID and appName is empty.
```

Do i have to set the app id and name manually?

I don't have any problem with other methods, such as `VersionCheck.needUpdate`, it fetches the correct versioning from the stores.

Thanks.

`"react-native": "0.57.5"`

**Comment by btmaster** [comment]
I have the same issue, any news on this?

**Comment by kimxogus** [comment]
[getStoreUrl](https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check/src/getStoreUrl.js#L36) in ios requires them and [appStoreProvider](https://github.com/kimxogus/react-native-version-check/blob/master/packages/react-native-version-check/src/providers/appStore.js#L31) doesn't because lookup api is used to get ios app version.
You need to set them to get store url which is accessible by user.

**Comment by jenskuhrjorgensen** [comment]
@kimxogus So `appID` and `appName` are required when calling `getStoreUrl` (and `getAppStoreUrl`)? The example in the README calls `getStoreUrl` with no parameters, so I thought I could too. 

I'm really looking forward to improve my previous implementation with this lib! :D

**Comment by saraswathirbt** [comment]
I am also facing the same error in IOS  
const playStoreUrl = await VersionCheck.getStoreUrl(appId, appName) is this is the correct way to use the getStoreUrl() can any one help me to solve this error.
 Thanks in advance

**Comment by jenskuhrjorgensen** [comment]
@saraswathirbt Thanks for clarifying. I've made a [PR](https://github.com/kimxogus/react-native-version-check/pull/64) that removes the need for the app name.

**Comment by anshif10** [comment]
> parameters

how i get appID
